# Workflow for deploying your Vite site to GitHub Pages using GitHub Actions deployment
name: Deploy Vite Site to GitHub Pages

on:
  push:
    branches: ["main"] # Trigger on pushes to your main branch
  workflow_dispatch: # Allows manual trigger

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy: # Renamed job for clarity
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Or your specific Node.js version (e.g., '20')

      - name: Install dependencies
        run: npm ci # 'npm ci' is generally preferred for CI environments

      - name: Build your Vite site
        run: npm run build # This command generates your static files in ./dist

      - name: Setup Pages
        uses: actions/configure-pages@v5 # This action sets up the Pages environment

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist" # IMPORTANT: Only upload the built 'dist' directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
